const cars = [
    {
        id:"1",
        name:"نيسان",
        model:"صني",
        year:"2019",
        cost:"50",
        date:"15/dec-18/dec"
    },
    {
        id:"2",
        name:"نيسان",
        model:"ليف",
        year:"2019",
        cost:"50",
        date:"13/dec-18/dec"
    },
    {
        id:"3",
        name:"نيسان",
        model:"باجيرو",
        year:"2019",
        cost:"100",
        date:"15/dec-20/dec"
    },
    {
        id:"4",
        name:"هوندا",
        model:"سيفك",
        year:"2020",
        cost:"40",
        date:"n/a"
    },
    {
        id:"5",
        name:"هونداي",
        model:"اكسنت",
        year:"2018",
        cost:"50",
        date:"10/dec-19/dec"
    }
]